"""inicial

Revision ID: 0001
Revises:
Create Date: 2026-08-09 12:58:21.050813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('pagarme_customer_id', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_table('recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.Enum('campo', 'quiosque', name='tiporecurso'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.Column('papel', sa.Enum('admin', 'atendente', name='papelstaff'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Integer(), nullable=False),
    sa.Column('hora_fim', sa.Integer(), nullable=False),
    sa.Column('valor_mensal_centavos', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'pausada', 'inadimplente', 'cancelada', name='assinaturastatus'), nullable=False),
    sa.Column('pagarme_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('proxima_cobranca', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('entidade', sa.String(length=40), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('dados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bloqueios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faixas_preco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('dias_semana', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('hora_inicio', sa.Integer(), nullable=False),
    sa.Column('hora_fim', sa.Integer(), nullable=False),
    sa.Column('preco_centavos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('nome_avulso', sa.String(length=120), nullable=True),
    sa.Column('celular_avulso', sa.String(length=20), nullable=True),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pendente_pagamento', 'confirmada', 'concluida', 'cancelada', 'expirada', name='reservastatus'), nullable=False),
    sa.Column('origem', sa.Enum('online', 'balcao', 'mensalista', name='reservaorigem'), nullable=False),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('assinatura_id', sa.Integer(), nullable=True),
    sa.Column('pacote_grupo_id', sa.String(length=36), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_pacote_grupo_id'), 'reservas', ['pacote_grupo_id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.Column('assinatura_id', sa.Integer(), nullable=True),
    sa.Column('metodo', sa.Enum('pix', 'cartao', 'dinheiro', 'pix_manual', name='metodopagamento'), nullable=False),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'pago', 'falhou', 'estornado', name='pagamentostatus'), nullable=False),
    sa.Column('pagarme_order_id', sa.String(length=64), nullable=True),
    sa.Column('pagarme_charge_id', sa.String(length=64), nullable=True),
    sa.Column('pago_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registrado_por_staff_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Adicionado manualmente (não gerado pelo autogenerate): extensão
    # btree_gist e constraints EXCLUDE anti-double-booking (spec §3). ---
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE reservas ADD CONSTRAINT reservas_sem_sobreposicao
        EXCLUDE USING gist (recurso_id WITH =, tstzrange(inicio, fim) WITH &&)
        WHERE (status IN ('pendente_pagamento','confirmada'))
        """
    )
    op.execute(
        """
        ALTER TABLE bloqueios ADD CONSTRAINT bloqueios_sem_sobreposicao
        EXCLUDE USING gist (recurso_id WITH =, tstzrange(inicio, fim) WITH &&)
        """
    )


def downgrade() -> None:
    op.execute("ALTER TABLE bloqueios DROP CONSTRAINT IF EXISTS bloqueios_sem_sobreposicao")
    op.execute("ALTER TABLE reservas DROP CONSTRAINT IF EXISTS reservas_sem_sobreposicao")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_reservas_pacote_grupo_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_table('faixas_preco')
    op.drop_table('bloqueios')
    op.drop_table('auditoria')
    op.drop_table('assinaturas')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_table('recursos')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###

    # --- Adicionado manualmente: drop_table não remove os tipos ENUM do
    # Postgres criados para as colunas — removê-los explicitamente evita
    # `DuplicateObjectError` num upgrade posterior. ---
    bind = op.get_bind()
    sa.Enum(name='tiporecurso').drop(bind, checkfirst=True)
    sa.Enum(name='papelstaff').drop(bind, checkfirst=True)
    sa.Enum(name='assinaturastatus').drop(bind, checkfirst=True)
    sa.Enum(name='reservastatus').drop(bind, checkfirst=True)
    sa.Enum(name='reservaorigem').drop(bind, checkfirst=True)
    sa.Enum(name='metodopagamento').drop(bind, checkfirst=True)
    sa.Enum(name='pagamentostatus').drop(bind, checkfirst=True)
